version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/electron-ui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    open-pull-requests-limit: 5
    reviewers:
      - "sakho13"
    target-branch: "develop"
